-- MySQL Script generated by MySQL Workbench
-- 09/05/17 13:54:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mecanica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mecanica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mecanica` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mecanica` ;

-- -----------------------------------------------------
-- Table `mecanica`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `cpf` VARCHAR(14) NULL,
  `telefone` VARCHAR(20) NULL,
  `rua` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` CHAR(2) NULL,
  `numero` VARCHAR(6) NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` VARCHAR(12) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL,
  `preco` VARCHAR(45) NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`carro` (
  `idcarro` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(10) NULL,
  `marca` VARCHAR(45) NULL,
  `carro` VARCHAR(45) NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idcarro`),
  INDEX `fk_carro_cliente_idx` (`cliente_idcliente` ASC),
  CONSTRAINT `fk_carro_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mecanica`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `especializacao` VARCHAR(45) NULL,
  PRIMARY KEY (`idfuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mecanica`.`ordem_de_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mecanica`.`ordem_de_servico` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `produto_idproduto` INT NOT NULL,
  `data` DATE NULL,
  `preco` VARCHAR(45) NULL,
  `carro_idcarro` INT NOT NULL,
  `funcionario_idfuncionario` INT NOT NULL,
  INDEX `fk_produto_has_carro_produto1_idx` (`produto_idproduto` ASC),
  PRIMARY KEY (`idvenda`, `produto_idproduto`, `carro_idcarro`, `funcionario_idfuncionario`),
  INDEX `fk_ordem_de_servico_carro1_idx` (`carro_idcarro` ASC),
  INDEX `fk_ordem_de_servico_funcionario1_idx` (`funcionario_idfuncionario` ASC),
  CONSTRAINT `fk_produto_has_carro_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `mecanica`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_de_servico_carro1`
    FOREIGN KEY (`carro_idcarro`)
    REFERENCES `mecanica`.`carro` (`idcarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_de_servico_funcionario1`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `mecanica`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
