insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Arne', '2443339866', '21-414-8309', '2nd', 'Denver', 'CO', '46', 'Lane', '9876459821');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Bertrando', '2623196346', '31-974-8738', 'Stephen', 'West Palm Beach', 'FL', '24', 'Junction', '2386196518');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Meggi', '0078544963', '83-800-7109', 'Buena Vista', 'Mobile', 'AL', '99753', 'Park', '3999162074');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Demetris', '2828907694', '24-615-7831', 'Manley', 'New Orleans', 'LA', '6809', 'Road', '9459757588');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Carita', '7231805434', '90-217-1121', 'Vahlen', 'Virginia Beach', 'VA', '0132', 'Road', '5838909447');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Goldie', '8341707012', '83-694-5984', 'Cherokee', 'New York City', 'NY', '51', 'Parkway', '0410516066');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Zolly', '6679042755', '73-591-5765', 'Kensington', 'Jacksonville', 'FL', '246', 'Point', '7898877829');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Craggie', '4132729907', '72-890-0514', 'Oakridge', 'Shreveport', 'LA', '03', 'Hill', '7561320507');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Conrade', '0691687110', '45-121-8280', 'Lyons', 'Panama City', 'FL', '7', 'Street', '7020251447');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Vivianna', '9129239761', '95-010-1610', 'Anderson', 'Seattle', 'WA', '11050', 'Drive', '3284013334');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Georgine', '1410587355', '03-212-7337', 'Monterey', 'Hartford', 'CT', '39172', 'Hill', '8906780532');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Antonius', '4911902795', '87-931-9170', 'Main', 'Brooklyn', 'NY', '55347', 'Hill', '2626842214');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Gnni', '8862418205', '35-954-2102', 'Gina', 'Sparks', 'NV', '2', 'Alley', '3617620507');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Case', '4384061056', '56-283-9047', 'Stoughton', 'Montgomery', 'AL', '68934', 'Court', '9307359695');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Tomlin', '3169663852', '11-368-0209', 'Morningstar', 'Fresno', 'CA', '545', 'Park', '7599157964');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Chip', '0164898808', '33-905-0757', '8th', 'Memphis', 'TN', '123', 'Road', '9407946088');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Gunar', '3054506525', '54-163-5451', 'Elgar', 'Norfolk', 'VA', '378', 'Point', '9166695465');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Vanny', '4695849852', '78-373-9945', 'Northview', 'El Paso', 'TX', '6', 'Pass', '9451075984');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Harriette', '2613350393', '35-931-1238', 'Fremont', 'Las Vegas', 'NV', '96', 'Parkway', '9119305680');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Manny', '8783680802', '47-818-8345', 'Cambridge', 'Peoria', 'IL', '636', 'Circle', '8410162520');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Kliment', '6752291357', '68-650-5840', 'Hudson', 'Augusta', 'GA', '093', 'Junction', '9726844576');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Mab', '9745075213', '03-319-5565', 'Continental', 'New York City', 'NY', '4673', 'Circle', '4381404173');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Dall', '2698043024', '10-527-7749', 'Lotheville', 'Seattle', 'WA', '07471', 'Parkway', '5731672172');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Fowler', '8095273759', '58-684-0267', 'Pepper Wood', 'Billings', 'MT', '8697', 'Way', '6500482913');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Johnny', '2728528780', '38-814-3666', 'Commercial', 'Phoenix', 'AZ', '627', 'Crossing', '8013195147');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Maurise', '7502599207', '73-205-5909', 'Hoepker', 'Wilmington', 'DE', '70493', 'Court', '8720475675');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Letti', '5861398380', '55-073-8162', 'Declaration', 'Minneapolis', 'MN', '19823', 'Way', '1855448696');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Davie', '7989128357', '41-977-2779', 'High Crossing', 'Chicago', 'IL', '5', 'Avenue', '8213803345');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Lauren', '2801042617', '11-528-1152', 'Randy', 'Pittsburgh', 'PA', '448', 'Terrace', '9272353688');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Ofelia', '2348026988', '89-895-2510', 'Straubel', 'Ogden', 'UT', '5', 'Lane', '1145766439');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Mela', '3520655322', '18-595-6620', 'Northport', 'Houston', 'TX', '06715', 'Point', '9617907755');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Hart', '4494067245', '82-918-3129', 'Algoma', 'Wilkes Barre', 'PA', '16', 'Circle', '9671195059');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Alberto', '8560184880', '92-456-1778', 'Cherokee', 'Fort Lauderdale', 'FL', '1', 'Trail', '2740223455');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Estrellita', '9019976311', '75-705-8599', 'Lerdahl', 'Washington', 'DC', '9', 'Hill', '5945486620');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Sergent', '2194908714', '36-827-1872', 'Muir', 'Philadelphia', 'PA', '610', 'Street', '4817551895');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Feodora', '4091734871', '44-909-1902', 'Claremont', 'Evansville', 'IN', '94151', 'Crossing', '2790409358');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Ardine', '5153212971', '28-132-5884', 'American Ash', 'Wilmington', 'DE', '55885', 'Avenue', '0730929752');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Teresita', '9218912879', '98-300-8572', 'John Wall', 'Pittsburgh', 'PA', '5', 'Junction', '4679924977');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Cale', '2438168617', '65-313-5514', 'Moland', 'Philadelphia', 'PA', '22050', 'Road', '5053544441');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Wilie', '4217363524', '58-057-0299', 'Thompson', 'Chicago', 'IL', '5', 'Hill', '2134009616');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Pietrek', '7717219468', '20-051-1934', 'Mesta', 'Davenport', 'IA', '4929', 'Parkway', '2209088003');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Jesse', '1926863682', '76-193-0351', 'Main', 'Jamaica', 'NY', '51', 'Road', '5080171642');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Brandtr', '4176608560', '66-281-1449', 'Continental', 'Washington', 'DC', '6', 'Junction', '6749414850');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Delcine', '6267276899', '70-140-2495', 'Mosinee', 'Washington', 'DC', '3', 'Hill', '4611723127');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Othelia', '6313162609', '83-449-7654', 'Mcguire', 'Oklahoma City', 'OK', '989', 'Court', '0719497655');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Meghann', '3702958444', '71-068-1534', 'Trailsway', 'Seattle', 'WA', '711', 'Junction', '6560877868');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Shell', '5433907082', '71-339-9556', 'Dryden', 'Longview', 'TX', '321', 'Junction', '6309208810');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Lorrayne', '8764875962', '43-072-1303', 'Tennessee', 'Pasadena', 'CA', '5', 'Lane', '0145550621');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Roderic', '1350144320', '47-437-5155', 'Melvin', 'Alexandria', 'VA', '27', 'Point', '0180403753');
insert into cliente (nome, cpf, telefone, rua, cidade, estado, numero, bairro, cep) values ('Wallache', '3289408590', '78-461-4323', 'Summerview', 'New York City', 'NY', '4', 'Circle', '5045373382');


insert into funcionario (nome, especializacao) values ('Jordain', 'carburação');
insert into funcionario (nome, especializacao) values ('Sonya', 'troca de correia');
insert into funcionario (nome, especializacao) values ('Barb', 'carburação');
insert into funcionario (nome, especializacao) values ('Sissie', 'troca de óleo');
insert into funcionario (nome, especializacao) values ('Gill', 'elétrica');
insert into funcionario (nome, especializacao) values ('Tedra', 'torneiro');
insert into funcionario (nome, especializacao) values ('Gerta', 'elétrica');
insert into funcionario (nome, especializacao) values ('Halli', 'torneiro');
insert into funcionario (nome, especializacao) values ('Sissy', 'alinhamento');
insert into funcionario (nome, especializacao) values ('Prescott', 'torneiro');
insert into funcionario (nome, especializacao) values ('Ashli', 'troca de óleo');
insert into funcionario (nome, especializacao) values ('Martyn', 'elétrica');
insert into funcionario (nome, especializacao) values ('Sara-ann', 'carburação');
insert into funcionario (nome, especializacao) values ('Joelie', 'troca de correia');
insert into funcionario (nome, especializacao) values ('Roanne', 'elétrica');
insert into funcionario (nome, especializacao) values ('Anallise', 'torneiro');
insert into funcionario (nome, especializacao) values ('Helene', 'elétrica');
insert into funcionario (nome, especializacao) values ('Ramon', 'injeção');
insert into funcionario (nome, especializacao) values ('Marina', 'troca de correia');
insert into funcionario (nome, especializacao) values ('Karlie', 'alinhamento');
insert into funcionario (nome, especializacao) values ('Nadeen', 'troca de correia');
insert into funcionario (nome, especializacao) values ('Lauritz', 'elétrica');
insert into funcionario (nome, especializacao) values ('Ali', 'troca de correia');
insert into funcionario (nome, especializacao) values ('Baillie', 'troca de correia');
insert into funcionario (nome, especializacao) values ('Cesare', 'troca de óleo');
insert into funcionario (nome, especializacao) values ('Rutledge', 'injeção');
insert into funcionario (nome, especializacao) values ('Karole', 'troca de óleo');
insert into funcionario (nome, especializacao) values ('Shandie', 'torneiro');
insert into funcionario (nome, especializacao) values ('Katherina', 'troca de óleo');
insert into funcionario (nome, especializacao) values ('Kendrick', 'troca de óleo');
insert into funcionario (nome, especializacao) values ('Bunni', 'injeção');
insert into funcionario (nome, especializacao) values ('Taffy', 'troca de óleo');
insert into funcionario (nome, especializacao) values ('Lolly', 'injeção');
insert into funcionario (nome, especializacao) values ('Eugenia', 'troca de correia');
insert into funcionario (nome, especializacao) values ('Lincoln', 'injeção');
insert into funcionario (nome, especializacao) values ('Shanna', 'elétrica');
insert into funcionario (nome, especializacao) values ('Griselda', 'elétrica');
insert into funcionario (nome, especializacao) values ('Patience', 'torneiro');
insert into funcionario (nome, especializacao) values ('Brianna', 'carburação');
insert into funcionario (nome, especializacao) values ('Karlan', 'torneiro');
insert into funcionario (nome, especializacao) values ('Ward', 'alinhamento');
insert into funcionario (nome, especializacao) values ('Sybila', 'troca de correia');
insert into funcionario (nome, especializacao) values ('Ave', 'carburação');
insert into funcionario (nome, especializacao) values ('Lezley', 'troca de óleo');
insert into funcionario (nome, especializacao) values ('Dita', 'carburação');
insert into funcionario (nome, especializacao) values ('Merry', 'elétrica');
insert into funcionario (nome, especializacao) values ('Orbadiah', 'injeção');
insert into funcionario (nome, especializacao) values ('Cliff', 'troca de correia');
insert into funcionario (nome, especializacao) values ('Bartlett', 'elétrica');
insert into funcionario (nome, especializacao) values ('Carolina', 'troca de óleo');



insert into produto (descricao, preco) values ('tensor/correia', 171.87);
insert into produto (descricao, preco) values ('filtro de ar', 30.71);
insert into produto (descricao, preco) values ('tensor/correia', 127.42);
insert into produto (descricao, preco) values ('bobina de ignição', 224.04);
insert into produto (descricao, preco) values ('spark pug', 295.08);
insert into produto (descricao, preco) values ('bobina de ignição', 36.12);
insert into produto (descricao, preco) values ('limpa ar condicionado', 277.22);
insert into produto (descricao, preco) values ('conversor', 251.91);
insert into produto (descricao, preco) values ('filtro de óleo', 61.17);
insert into produto (descricao, preco) values ('tensor/correia', 84.90);
insert into produto (descricao, preco) values ('spark pug', 249.13);
insert into produto (descricao, preco) values ('bobina de ignição', 9.42);
insert into produto (descricao, preco) values ('bobina de ignição', 209.46);
insert into produto (descricao, preco) values ('filtro de ar', 178.71);
insert into produto (descricao, preco) values ('cabos vela', 0.81);
insert into produto (descricao, preco) values ('rotor', 83.20);
insert into produto (descricao, preco) values ('limpa ar condicionado', 253.71);
insert into produto (descricao, preco) values ('limpa ar condicionado', 238.63);
insert into produto (descricao, preco) values ('filtro de ar', 34.10);
insert into produto (descricao, preco) values ('tensor/correia', 111.35);
insert into produto (descricao, preco) values ('cabos de ignição resistivos', 249.41);
insert into produto (descricao, preco) values ('limpa ar condicionado', 198.13);
insert into produto (descricao, preco) values ('limpa ar condicionado', 125.34);
insert into produto (descricao, preco) values ('rotor', 177.85);
insert into produto (descricao, preco) values ('spark pug', 38.11);
insert into produto (descricao, preco) values ('lubrificante para motor', 115.63);
insert into produto (descricao, preco) values ('lubrificante para motor', 52.93);
insert into produto (descricao, preco) values ('tampa dist.', 50.14);
insert into produto (descricao, preco) values ('filtro de combustível', 4.69);
insert into produto (descricao, preco) values ('filtro de cabine', 80.75);
insert into produto (descricao, preco) values ('filtro de ar', 201.06);
insert into produto (descricao, preco) values ('filtro de cabine', 283.85);
insert into produto (descricao, preco) values ('filtro de ar', 295.38);
insert into produto (descricao, preco) values ('cabos vela', 202.61);
insert into produto (descricao, preco) values ('vela de ignição', 45.63);
insert into produto (descricao, preco) values ('rotor', 85.36);
insert into produto (descricao, preco) values ('filtro de óleo', 176.66);
insert into produto (descricao, preco) values ('cabos de ignição resistivos', 101.96);
insert into produto (descricao, preco) values ('kit tensor', 232.67);
insert into produto (descricao, preco) values ('limpa ar condicionado', 100.44);
insert into produto (descricao, preco) values ('filtro de óleo', 76.71);
insert into produto (descricao, preco) values ('cabos de ignição resistivos', 98.99);
insert into produto (descricao, preco) values ('cabos vela', 162.72);
insert into produto (descricao, preco) values ('limpa ar condicionado', 209.04);
insert into produto (descricao, preco) values ('filtro de cabine', 33.77);
insert into produto (descricao, preco) values ('kit tensor', 14.84);
insert into produto (descricao, preco) values ('filtro de óleo', 139.95);
insert into produto (descricao, preco) values ('cabos de ignição resistivos', 127.01);
insert into produto (descricao, preco) values ('filtro de combustível', 18.47);
insert into produto (descricao, preco) values ('lubrificante para motor', 252.70);



insert into carro (placa, marca, carro, cliente_idcliente) values ('NAT-9400', 'Shelby', 'GT350', 1);
insert into carro (placa, marca, carro, cliente_idcliente) values ('ISW-4082', 'Plymouth', 'Colt Vista', 2);
insert into carro (placa, marca, carro, cliente_idcliente) values ('MVH-2967', 'Suzuki', 'XL-7', 3);
insert into carro (placa, marca, carro, cliente_idcliente) values ('ACK-9994', 'Hyundai', 'Elantra', 4);
insert into carro (placa, marca, carro, cliente_idcliente) values ('MOE-2205', 'Eagle', 'Talon', 5);
insert into carro (placa, marca, carro, cliente_idcliente) values ('MYA-0546', 'Plymouth', 'Acclaim', 6);
insert into carro (placa, marca, carro, cliente_idcliente) values ('NEW-5344', 'Acura', 'Integra', 7);
insert into carro (placa, marca, carro, cliente_idcliente) values ('MYM-3048', 'Dodge', 'Dakota', 8);
insert into carro (placa, marca, carro, cliente_idcliente) values ('NAE-4880', 'Subaru', 'Impreza', 9);
insert into carro (placa, marca, carro, cliente_idcliente) values ('KLR-7339', 'Mercedes-Benz', 'SL-Class', 10);
insert into carro (placa, marca, carro, cliente_idcliente) values ('IAE-6883', 'Honda', 'Insight', 11);
insert into carro (placa, marca, carro, cliente_idcliente) values ('IAO-2833', 'Honda', 'S2000', 12);
insert into carro (placa, marca, carro, cliente_idcliente) values ('NEY-5082', 'GMC', 'Vandura G1500', 13);
insert into carro (placa, marca, carro, cliente_idcliente) values ('JZF-8549', 'Mercedes-Benz', 'S-Class', 14);
insert into carro (placa, marca, carro, cliente_idcliente) values ('NFB-2588', 'Dodge', 'Stratus', 15);
insert into carro (placa, marca, carro, cliente_idcliente) values ('FKU-4660', 'Mazda', 'Protege', 16);
insert into carro (placa, marca, carro, cliente_idcliente) values ('NEJ-9377', 'Chevrolet', 'Impala', 17);
insert into carro (placa, marca, carro, cliente_idcliente) values ('ATB-7976', 'Toyota', 'Prius', 18);
insert into carro (placa, marca, carro, cliente_idcliente) values ('AAF-1681', 'Cadillac', 'Seville', 19);
insert into carro (placa, marca, carro, cliente_idcliente) values ('KFB-1484', 'Lincoln', 'Navigator L', 20);
insert into carro (placa, marca, carro, cliente_idcliente) values ('KAA-8956', 'Hummer', 'H3', 21);
insert into carro (placa, marca, carro, cliente_idcliente) values ('MSU-1466', 'Hummer', 'H1', 22);
insert into carro (placa, marca, carro, cliente_idcliente) values ('KEK-7901', 'Ford', 'Thunderbird', 23);
insert into carro (placa, marca, carro, cliente_idcliente) values ('HON-2884', 'Infiniti', 'G25', 24);
insert into carro (placa, marca, carro, cliente_idcliente) values ('NBA-1884', 'Audi', 'A4', 25);
insert into carro (placa, marca, carro, cliente_idcliente) values ('NDA-4571', 'Cadillac', 'Catera', 26);
insert into carro (placa, marca, carro, cliente_idcliente) values ('NBL-7820', 'Nissan', 'Maxima', 27);
insert into carro (placa, marca, carro, cliente_idcliente) values ('EVE-4904', 'Acura', 'NSX', 28);
insert into carro (placa, marca, carro, cliente_idcliente) values ('LVT-1840', 'Lincoln', 'LS', 29);
insert into carro (placa, marca, carro, cliente_idcliente) values ('HSI-4309', 'Infiniti', 'IPL G', 30);
insert into carro (placa, marca, carro, cliente_idcliente) values ('IMU-7132', 'Ford', 'F150', 31);
insert into carro (placa, marca, carro, cliente_idcliente) values ('HQA-5637', 'Porsche', '911', 32);
insert into carro (placa, marca, carro, cliente_idcliente) values ('KFF-6186', 'Chevrolet', 'Corvette', 33);
insert into carro (placa, marca, carro, cliente_idcliente) values ('HPM-2592', 'Lamborghini', 'Gallardo', 34);
insert into carro (placa, marca, carro, cliente_idcliente) values ('KZM-1445', 'Pontiac', 'Sunbird', 35);
insert into carro (placa, marca, carro, cliente_idcliente) values ('HGZ-7792', 'Infiniti', 'Q', 36);
insert into carro (placa, marca, carro, cliente_idcliente) values ('JTW-3574', 'GMC', 'Savana 3500', 37);
insert into carro (placa, marca, carro, cliente_idcliente) values ('MWZ-6724', 'Pontiac', 'Turbo Firefly', 38);
insert into carro (placa, marca, carro, cliente_idcliente) values ('KNJ-5324', 'Pontiac', 'Grand Prix', 39);
insert into carro (placa, marca, carro, cliente_idcliente) values ('JAT-7761', 'Nissan', 'Pathfinder', 40);
insert into carro (placa, marca, carro, cliente_idcliente) values ('NAR-7855', 'Volvo', 'C70', 41);
insert into carro (placa, marca, carro, cliente_idcliente) values ('NDA-8462', 'Hummer', 'H1', 42);
insert into carro (placa, marca, carro, cliente_idcliente) values ('MXK-5979', 'Mercury', 'Grand Marquis', 43);
insert into carro (placa, marca, carro, cliente_idcliente) values ('GXC-3227', 'Ford', 'E-Series', 44);
insert into carro (placa, marca, carro, cliente_idcliente) values ('MFG-3739', 'Porsche', 'Cayenne', 45);
insert into carro (placa, marca, carro, cliente_idcliente) values ('LVI-8828', 'Rolls-Royce', 'Phantom', 46);
insert into carro (placa, marca, carro, cliente_idcliente) values ('MTI-4432', 'Ford', 'LTD Crown Victoria', 47);
insert into carro (placa, marca, carro, cliente_idcliente) values ('MTW-6579', 'Pontiac', 'Grand Am', 48);
insert into carro (placa, marca, carro, cliente_idcliente) values ('KAR-2345', 'GMC', 'Yukon XL 1500', 49);
insert into carro (placa, marca, carro, cliente_idcliente) values ('NAT-9000', 'Ford', 'Taurus', 50);




insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2011/01/20', '72.47', 1, 1);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2014/03/13', '30.24', 2, 2);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2013/10/25', '88.96', 3, 3);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2010/08/07', '31.54', 4, 4);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2012/12/01', '84.87', 5, 5);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2017/01/02', '45.76', 6, 6);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2011/07/12', '60.10', 7, 7);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2012/08/25', '37.96', 8, 8);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2013/03/27', '20.84', 9, 9);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2009/04/01', '14.21', 10, 10);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2013/04/14', '61.55', 11, 11);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2012/12/26', '80.16', 12, 12);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2012/12/27', '98.07', 13, 13);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2013/07/30', '68.44', 14, 14);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2011/06/11', '90.76', 15, 15);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2015/05/31', '69.24', 16, 16);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2009/10/17', '44.24', 17, 17);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2012/01/16', '50.96', 18, 18);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2008/06/23', '1.98', 19, 19);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2008/12/30', '26.44', 20, 20);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2012/04/22', '86.69', 21, 21);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2013/08/15', '86.21', 22, 22);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2015/06/29', '64.07', 23, 23);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2010/04/15', '71.22', 24, 24);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2010/08/26', '69.67', 25, 25);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2013/11/27', '76.73', 26, 26);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2016/04/10', '86.32', 27, 27);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2011/08/13', '17.87', 28, 28);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2010/06/25', '23.39', 29, 29);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2009/04/16', '63.34', 30, 30);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2009/03/18', '80.18', 31, 31);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2012/08/14', '26.96', 32, 32);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2014/10/03', '69.46', 33, 33);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2015/03/13', '1.95', 34, 34);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2008/11/17', '97.65', 35, 35);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2009/08/13', '74.49', 36, 36);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2017/06/16', '43.83', 37, 37);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2015/07/12', '22.43', 38, 38);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2009/01/24', '63.99', 39, 39);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2012/08/13', '61.10', 40, 40);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2010/10/23', '75.32', 41, 41);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2013/05/02', '36.35', 42, 42);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2012/05/31', '87.62', 43, 43);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2013/03/29', '48.92', 44, 44);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2015/05/29', '50.65', 45, 45);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2011/03/12', '84.59', 46, 46);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2017/04/03', '99.79', 47, 47);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2010/06/07', '56.47', 48, 48);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2011/11/10', '11.95', 49, 49);
insert into ordem_servico (data, preco, funcionario_idfuncionario, carro_idcarro) values ('2009/06/18', '18.85', 50, 50);




insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (1, 1);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (2, 2);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (3, 3);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (4, 4);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (5, 5);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (6, 6);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (7, 7);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (8, 8);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (9, 9);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (10, 10);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (11, 11);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (12, 12);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (13, 13);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (14, 14);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (15, 15);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (16, 16);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (17, 17);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (18, 18);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (19, 19);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (20, 20);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (21, 21);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (22, 22);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (23, 23);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (24, 24);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (25, 25);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (26, 26);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (27, 27);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (28, 28);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (29, 29);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (30, 30);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (31, 31);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (32, 32);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (33, 33);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (34, 34);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (35, 35);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (36, 36);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (37, 37);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (38, 38);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (39, 39);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (40, 40);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (41, 41);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (42, 42);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (43, 43);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (44, 44);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (45, 45);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (46, 46);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (47, 47);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (48, 48);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (49, 49);
insert into ordem_servico_has_produto (ordem_servico_idordem_servico, produto_idproduto) values (50, 50);



